### ISSUE TITLE
Add New Task

### ISSUE THREAD

**Issue by kunalkashyap855** [kunalkashyap855/kanban#1]
## Add new task implementation 

- Create a **text field** with a **Submit/Add** button in which the user can enter the new task.
- On pressing the "Add" button, the task should get added to the **Not Started** column.

**Comment by noellered** [comment]
I'd like to take this on if it's available.

**Comment by abhinav5481** [comment]
Hi Kunal,
I would like to work on this issue under CrossWoc challenge. Could you please assign this to me?

**Comment by VedVyapak** [comment]
Hey Kunal, I would like to work on the issue. Could you assign this to me?

**Comment by jainh6148** [comment]
Hi Sir, I would like to contribute to this project can you assign it to me. I have experience in working in ReactJS

**Comment by ArkajyotiChakraborty** [comment]
Good Evening Kunal Sir, I would like to contribute in this project, i have a good experience of working in react js .

**Comment by arbazalam01** [comment]
Can you assign this task to me.

**Comment by abhinav5481** [comment]
> Hi Kunal,
> I would like to work on this issue under CrossWoc challenge. Could you please assign this to me?

My PR which got successfully merged today morning won't be counted for the leaderboard (I was unaware about it).  Could you assign this issue to me?

**Comment by Hritikkumar** [comment]
Hi Sir, I would like to contribute to this project. Kindly assign it to me.

**Comment by kunalkashyap855** [comment]
> Hey Kunal, I would like to work on the issue. Could you assign this to me?

Hi Ved, I'm assigning this issue to you. Please go ahead.
Also, if there are any issues or if you want to discuss anything, please do that on the [discord channel](https://discord.gg/ubV2SKPK).

**Deadline: 16th February, 1 PM** If the issue is not closed by then, it will be passed on to the next person.

**Comment by kunalkashyap855** [comment]
> I'd like to take this on if it's available.

Thank you for showing your interest of contributing to this project. However, this project is part of an open source competition in my college and only students participating in that can contribute to it. (Till the competition is active)

That's why I couldn't assign it to you. I hope you'll understand.

**Comment by abhisheklalwani26** [comment]
Can you assign me this issue

**Comment by VedVyapak** [comment]
Hey Kunal, please check your discord direct messages

**Comment by kunalkashyap855** [comment]
Deadline for @VedVyapak has been increased till **Tomorrow, 17th Feb, 8 PM**.

**Comment by arbazalam01** [comment]
Is this issue still open

**Comment by kunalkashyap855** [comment]
Yes, it is. Its assigned to @VedVyapak until tonight. If its not closed by then, I'll assign it to someone else.

> Is this issue still open

**Comment by kunalkashyap855** [comment]
@jainh6148 Are you interested in taking this up?

**Comment by arbazalam01** [comment]
Can i work on it

**Comment by kunalkashyap855** [comment]
> Can i work on it

Let's wait till 10 or 11 in the morning, if none of the the previous people reply, I'll assign it to you.

**Comment by jainh6148** [comment]
Yes, I will work on that issue.

**Comment by kunalkashyap855** [comment]
Okay, I have assigned the issue to @jainh6148.
Also, if there are any issues or if you want to discuss anything, please do that on the discord channel.

What do you think would be a good deadline?

> Yes, I will work on that issue.

**Comment by jainh6148** [comment]
Hi, I am working on an issue today and will complete it so from tomorrow I can start working on this so I think 22/02/21 would be fine if there is no problem.

**Comment by kunalkashyap855** [comment]
> Hi, I am working on an issue today and will complete it so from tomorrow I can start working on this so I think 22/02/21 would be fine if there is no problem.

Sounds good. Let's keep the deadline **22nd February, 6PM**.

**Comment by arbazalam01** [comment]
can i work on this issue

**Comment by kunalkashyap855** [comment]
@arbazalam01 Yes, I'm assigning it to you. Please go ahead.

Deadline: **26th February, 8PM**.

Please let me know if you need any help or if there's any issue.

**Comment by abhinav5481** [comment]
Hey Kunal,
I would like to work on this issue. if It is still open could you please assign it to me?

**Comment by kunalkashyap855** [comment]
@abhinav5481 Yes, go ahead.
