### ISSUE TITLE
Edit a Task

### ISSUE THREAD

**Issue by abhinav5481** [kunalkashyap855/kanban#11]
Add a feature to make changes in any task.

**Comment by abhinav5481** [comment]
Hi @kunalkashyap855 
I would like to work on this issue as part of crossWoc'21. Please assign it to me.

**Comment by kunalkashyap855** [comment]
Cool, you can work on it. Should be easy now that you've implemented the add new task one already.

**Comment by kunalkashyap855** [comment]
Great work! @abhinav5481
