### ISSUE TITLE
Delete Any Task

### ISSUE THREAD

**Issue by abhinav5481** [kunalkashyap855/kanban#13]
Add a feature to delete any task.

**Comment by abhinav5481** [comment]
Hi @kunalkashyap855 ,
I would like to work on this. Could you please assign it to me?

**Comment by kunalkashyap855** [comment]
I've added the labels. You can now work on this.

> Hi @kunalkashyap855 ,
> I would like to work on this. Could you please assign it to me?

**Comment by kunalkashyap855** [comment]
I've merged the PR @abhinav5481
