### ISSUE TITLE
Front-end Design user signup & signin page

### ISSUE THREAD

**Issue by abhinav5481** [kunalkashyap855/kanban#15]
Design user `signup`  & `signin` page that would allow the user to login & signup. These features would make the app more meaningful & realistic.

**Comment by abhinav5481** [comment]
Hi @kunalkashyap855 
I would like to work on this issue as part of CrossWoc'2021. Please assign this task to me.

**Comment by kunalkashyap855** [comment]
Will you also implement the user signing and signup functionality?

**Comment by abhinav5481** [comment]
Yeah

**Comment by abhinav5481** [comment]
My idea is to make the app more realistic by enhancing the utility.

**Comment by kunalkashyap855** [comment]
Okay, assigning it to you. Go ahead.
