### ISSUE TITLE
Integrate User tasks with the back-end.

### ISSUE THREAD

**Issue by abhinav5481** [kunalkashyap855/kanban#19]
The user should be able to log in and view all his task.

**Comment by abhinav5481** [comment]
hi @kunalkashyap855 
I would like to work on this feature. Please assign it to me under crossWoc'21

**Comment by abhinav5481** [comment]
> hi @kunalkashyap855
> I would like to work on this feature. Please assign it to me under crossWoc'21

@kunalkashyap855

**Comment by kunalkashyap855** [comment]
Go ahead @abhinav5481
