### ISSUE TITLE
Draggables not working

### ISSUE THREAD

**Issue by kunalkashyap855** [kunalkashyap855/kanban#2]
- Not able to drag the draggable cards from one one column to another.
- Cards not displaying the content.

Most likely reason for the bug is data not being transferred correctly from the column component to the card component. Check if draggableId is correct for each card.

**Comment by abhinav5481** [comment]
Hi Kunal,
I would like to work on this issue for CrossWoc challenge. Could you please assign this issue to me?

**Comment by kunalkashyap855** [comment]
> Hi Kunal,
> I would like to work on this issue for CrossWoc challenge. Could you please assign this issue to me?

Hi Abhinav,
Yes, go ahead with this. And try completing it by **Sunday, 14th February, 8 PM**.

Also please join the project's [discord channel](https://discord.gg/KApR6fjx) for any further communication:

**Comment by kunalkashyap855** [comment]
@abhinav5481 good work! I guess it was pretty straightforward. I am closing this issue now.
