### ISSUE TITLE
I will add name and photo of maintainer in the end of readme file of your repo

### ISSUE THREAD

**Issue by yashlikescode** [kunalkashyap855/kanban#8]
like the one mentioned below
![image](https://user-images.githubusercontent.com/66861659/110196850-45a66580-7e6d-11eb-8b79-2a2d8257ec35.png)

**Comment by kunalkashyap855** [comment]
Cool, Please go ahead @kmryashasvi . Try completing this by tonight.

**Comment by kunalkashyap855** [comment]
I have merged the PR. Good work! @kmryashasvi
